DECLARE @TABLE_NAME NVARCHAR(MAX)
DECLARE DeleteDBCursor CURSOR
FOR
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_CATALOG='nSoftId'
OPEN DeleteCursor
FETCH NEXT FROM DeleteDBCursor INTO @TABLE_NAME
WHILE @@FETCH_STATUS = 0
  BEGIN
	DECLARE @Sql NVARCHAR(MAX) ='TRUNCATE TABLE '
	SET @Sql = @Sql+@TABLE_NAME
	EXEC sp_executesql @Sql
    PRINT @TABLE_NAME
    FETCH NEXT FROM DeleteDBCursor INTO @TABLE_NAME
  END
CLOSE DeleteCursor
DEALLOCATE DeleteDBCursor